#!/bin/bash

# Ensure the current directory is within a Git repository
if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    echo "Warning! Not a Git repository !"
		echo "Please set up repo: git clone https://github.com/SouravB97/BasicCPU.git"
		echo "Setting STEM as current working directory."
		repo_root=$(pwd)
else 
		# Get the root directory of the Git repository
		repo_root=$(git rev-parse --show-toplevel)
fi

export STEM=$repo_root
source $STEM/.alias
chmod +x scripts/run_asm
chmod +x scripts/irun.bat
echo "Loaded env"
echo "\$STEM set to $STEM"

