#!/usr/bin/perl 
#exec("gvim -p design/CPU.v testbench/CPU_tb.v testbench/micro_code.hex scripts/micro_code_gen.pl design/BHVR/memory_bhvr.v design/register.v design/ALU_components.v &");
exec("gvim -c 'source ./scripts/open_session.vimrc' &");
