;;this is my code file
LDAR1 0
LDAR0 0xF0
LDA 2
LDB 3
ADD
MOV_A_MEM
INC_AR INC MOV_A_MEM
INC_AR INC MOV_A_MEM
INC_AR INC MOV_A_MEM
INC_AR INC MOV_A_MEM
INC_AR INC MOV_A_MEM
INC_AR INC MOV_A_MEM
INC_AR INC MOV_A_MEM
INC_AR INC MOV_A_MEM
INC_AR INC MOV_A_MEM
INC_AR INC MOV_A_MEM
HLT
